# Use custom format
format = """
┌─$username$hostname in $directory on $git_branch$git_status$git_state
└─$time """

[username]
style_user = "bold fg:30"
format = "[$user]($style)"
show_always = true

[hostname]
ssh_only = false
style = "bold fg:30"
format = "[@not-computer]($style)"

[directory]
truncate_to_repo = false
format = "[$path]($style)"

[git_branch]
style = "bold fg:42"
format = '([$symbol$branch ]($style))'

[git_status]
style = "bold fg:42"
format = '([\[$all_status$ahead_behind\] ]($style))'

[git_state]
style = "bold fg:42"
format = '([$state]($style))'

[time]
style = "bold fg:32"
format = "[$time ❯ ]($style)"
disabled = false
