name: CI test

on: push

jobs:
  build:
    name: test
    runs-on: ubuntu-20.04
    steps:
    - name: test tee /dev/stderr
      run : |
        set -x
        set -euo pipefail
        ls -la /dev
        seq 0 10 | tee /dev/stderr | xargs echo
